### PR TITLE
Added working demonstration source code

### PR DESCRIPTION
**Pull request by stappersg**
Under doc/ is now cfgdemo/ which has a working example.
Including a `config.yaml`.

### CODE REVIEW

**Comment by stappersg** [comment]
I'm not sure if  `doc/cfdemo/src/` is the proper place the (working) example code.

**Comment by stappersg** [comment]
At https://doc.rust-lang.org/cargo/guide/project-layout.html is documented that `examples/` is for examples.

**Comment by tailhook** [comment]
Yes. Examples directory is good enough for this kind of example.

**Comment by stappersg** [comment]
Closing because there is now #19

**Pull request closed without merging**
